name: Code Coverage

on:
    workflow_call:
        inputs:
            max_limit:
                type: string
                required: true
            min_limit:
                type: string
                required: true

env:
    DOTNET_VERSION: '10.0.x'
    buildConfiguration: Release
    coveragePath: ./coverage
    configFilename: .netconfig

jobs:
    code-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
            
            - name: Restore NuGet package
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration ${{ env.buildConfiguration }}

            - name: Run Code Coverage
              run: |
                dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" \
                    --configuration ${{ env.buildConfiguration }} --results-directory ${{ env.coveragePath }}

            - name: Create .netconfig File
              id: netconfig_name
              run: |
                echo '[ReportGenerator]
                  targetdir = "${{ env.coveragePath }}"
                  reporttypes = "Html_Dark;Cobertura;MarkdownSummary;MarkdownSummaryGithub"
                  verbosity = Verbose' > ${{ env.configFilename }}

            - name: Install dotnet tools
              run: |
                dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.5.4
                dotnet tool install -g dotnet-config --version 1.2.0
                export PATH="$PATH:$HOME/.dotnet/tools"

            - name: Generate Code Coverage Summary
              run: reportgenerator -reports:"**/coverage.cobertura.xml"

            - name: Publish Drop Artifacts
              uses: actions/upload-artifact@v7
              with:
                name: CoverageReport
                path: ${{ env.coveragePath }}

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.9'

            - name: Extract Coverage Names
              env:
                min_limit: ${{ inputs.min_limit }}
                max_limit: ${{ inputs.max_limit }}
              run: |
                python -c "
                import re, os
                    
                min_limit = int(os.getenv('min_limit'))
                max_limit = int(os.getenv('max_limit'))

                check_icon = '\u2705'
                warning_icon = '\u26A0'
                cross_icon = '\u274C'
                output_lines = ['# Coverage Table\\n\\n', '| Name | Percentage | |\\n', '| --- | --- | --- |\\n']

                file_path = '${{ env.coveragePath }}/SummaryGithub.md'
                output_file_path = '${{ env.coveragePath }}/extraction.md'

                with open(file_path, 'r') as file:
                    content = file.read()

                matches = re.findall(r'<details><summary>(.*?) - (\d+(?:\.\d+)?)%</summary>', content)

                project = matches[0][0]
                coverage_percentage = float(matches[0][1])
                icon = ''

                if coverage_percentage > max_limit:
                    icon = check_icon
                elif min_limit <= coverage_percentage <= max_limit:
                    icon = warning_icon
                else:
                    icon = cross_icon

                new_line = f'| {project} | {coverage_percentage}% | {icon} |'

                output_lines.append(f'{new_line}\\n')

                with open(output_file_path, 'w') as output_file:
                    output_file.writelines(output_lines)
                "

            - name: Write to Job Summary - Table
              run: cat ${{ env.coveragePath }}/extraction.md >> $GITHUB_STEP_SUMMARY

            - name: Write to Job Summary - Table
              run: cat ${{ env.coveragePath }}/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

            - name: Check line-rate in Cobertura.xml
              env:
                max_limit: ${{ inputs.max_limit }}
              run: |
                python - <<EOF
                import xml.etree.ElementTree as ET
                import os

                limit = int(os.getenv('max_limit'))

                cobertura_path = '${{ env.coveragePath }}/Cobertura.xml'

                tree = ET.parse(cobertura_path)
                root = tree.getroot()

                line_rate = round(float(root.attrib['line-rate']) * 100, 1)

                if line_rate < limit:
                    print(f'line-rate {line_rate} is below the limit of {limit}.')
                    exit(1)
                else:
                    print(f'line-rate {line_rate} is acceptable.')
                EOF