name: Code Coverage

on:
    workflow_call:
        inputs:
            coverage_threshold:
                type: number
                required: true

env:
    DOTNET_VERSION: '10.0.x'
    buildConfiguration: Release
    coveragePath: ./coverage
    configFilename: .netconfig

jobs:
    code-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
            
            - name: Restore NuGet package
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration ${{ env.buildConfiguration }}

            - name: Run Code Coverage
              run: |
                dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" \
                    --results-directory ${{ env.coveragePath }}

            - name: Create .netconfig File
              id: netconfig_name
              run: |
                echo '[ReportGenerator]
                  targetdir = "${{ env.coveragePath }}"
                  reporttypes - "Html_Dark;Cobertura;MarkdownSummary;MarkdownSummaryGithub"
                  verbosity = Verbose' > ${{ env.configFilename }}
            
            - name: Whoami
              run: whoami

            - name: List dotnet tools in root home
              run: ls -la /root/.dotnet/tools

            - name: List dotnet tools in user home
              run: ls -la /home/$(whoami)/.dotnet/tools

            - name: Generate Code Coverage Summary
              run: |
                dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.3.11
                dotnet tool install -g dotnet-config
                export PATH="$PATH:/root/.dotnet/tools"

                reportgenerator -reports:"**/coverage.cobertura.xml"

            - name: List report generated
              run: ls -la ${{ env.coveragePath }}

            - name: Publish Drop Artifacts
              uses: actions/upload-artifact@v7
              with:
                name: CoverageReport
                path: ${{ env.coveragePath }}

            - name: Write to Job Github Summary
              run: cat ${{ env.coveragePath }}/SummaryGithub.md

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'

            - name: Extract Coverage Names
              env:
                coverage_threshold: ${{ inputs.coverage_threshold }}
              run: |
                python -c "
                    import re, os
                    
                    threshold = int(os.getenv('coverage_threshold'))

                    check_icon = "OK"
                    dash_icon = "MMM"
                    cross_icon = "NOPE"

                    print(threshold)
                "
